on: push
name: Test

jobs:
    unity-editmode-test-mac:
        runs-on: ["self-hosted", "macos"]
        steps:
            - run: echo "Hello world!"

    unity-playmode-test-mac:
        runs-on: ["self-hosted", "macos"]
        steps:
            - run: echo "Hello world!"

    unity-editmode-test-win:
        runs-on: ["self-hosted", "windows"]
        steps:
            - run: echo "Hello world!"

    unity-playmode-test-win:
        runs-on: ["self-hosted", "windows"]
        env:
            UNITY_BINARY_PATH: "C:\\Program Files\\Unity\\Hub\\Editor\\2021.3.42f1\\Editor\\Unity.exe"
        steps:
            - run: echo "Hello world!"
            - run: "&\"${{env.UNITY_BINARY_PATH}}\" --batchmode --projectPath ${{github.workspace}} --runTests --testPlatform PlayMode"
